# Generated by Django 5.1.6 on 2025-03-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0005_item_item_type_item_x_position_item_y_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='buildings/')),
                ('locked_image', models.ImageField(upload_to='buildings/')),
                ('sustainability_score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='purchased_items',
        ),
        migrations.RemoveField(
            model_name='userinventory',
            name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='carbo_score',
            new_name='sustainability_score',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='item',
            name='y_position',
        ),
        migrations.CreateModel(
            name='UserBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlockables.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlockables.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MapSlot',
        ),
        migrations.DeleteModel(
            name='UserInventory',
        ),
    ]
