# Generated by Django 5.1.6 on 2025-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0007_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
