# Generated by Django 5.1.6 on 2025-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0009_building_x_building_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
