# Generated by Django 5.1.6 on 2025-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0009_building_x_building_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubbish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rubbish/')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('cleaned', models.BooleanField(default=False)),
                ('clean_cost', models.IntegerField(default=5)),
                ('sustainability_score', models.IntegerField(default=-2)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='max_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
