# Generated by Django 5.1.6 on 2025-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0010_item_max_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubbish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rubbish/')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('clean_cost', models.IntegerField(default=5)),
            ],
        ),
    ]
