# Generated by Django 5.1.3 on 2025-03-24 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0010_rubbish_item_max_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritem',
            old_name='user',
            new_name='useritem',
        ),
        migrations.RemoveField(
            model_name='rubbish',
            name='clean_cost',
        ),
        migrations.RemoveField(
            model_name='rubbish',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='rubbish',
            name='cleaned_at',
        ),
        migrations.AddField(
            model_name='building',
            name='size',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='useritem',
            name='size',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='UserRubbish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned', models.BooleanField(default=False)),
                ('clean_cost', models.IntegerField(default=5)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlockables.rubbish')),
                ('useritem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
