# Generated by Django 5.1.6 on 2025-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0011_rename_user_useritem_useritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
