# Generated by Django 5.1.6 on 2025-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0012_rubbish_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubbish',
            name='sustainability_score',
            field=models.IntegerField(default=-10),
        ),
    ]
