# Generated by Django 5.1.6 on 2025-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlockables', '0014_alter_rubbish_sustainability_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubbish',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
