# Generated by Django 5.1.5 on 2025-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('current_progress', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('reward', models.IntegerField(default=0)),
                ('lat_location', models.FloatField(default=0)),
                ('long_location', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('has_checked_in', models.BooleanField(default=False)),
            ],
        ),
    ]
