# Generated by Django 5.1.5 on 2025-02-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkin', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='lat_location',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='long_location',
        ),
        migrations.AddField(
            model_name='tasks',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Checkin.location'),
        ),
    ]
