# Generated by Django 5.1.5 on 2025-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='lat_location',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='long_location',
            field=models.FloatField(default=0),
        ),
    ]
