# Generated by Django 5.1.5 on 2025-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_lat_location_tasks_long_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='has_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
