# Generated by Django 5.1.3 on 2025-03-09 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_uploadedimage_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='tasks.tasks'),
        ),
    ]
