# Generated by Django 5.1.6 on 2025-03-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_tasks_user_tasks_user'),
        ('tasks', '0007_uploadedimage_uploaded_by'),
    ]

    operations = [
    ]
