# Generated by Django 5.1.3 on 2025-03-24 01:21

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_20250321_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=tasks.models.unique_file_name),
        ),
    ]
