# Generated by Django 5.1.5 on 2025-02-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collectable',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
