# Generated by Django 5.1.6 on 2025-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collectable',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='points',
            new_name='all_time_points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
    ]
