# Generated by Django 5.1.5 on 2025-03-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_collectable_delete_locations'),
        ('tasks', '0006_remove_tasks_user_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasks'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='task_assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
