# Generated by Django 5.1.5 on 2025-03-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_locations_customuser_collectables_owned'),
        ('home', '0005_customuser_selected_task_customuser_task_assign_date'),
    ]

    operations = [
    ]
