# Generated by Django 5.1.5 on 2025-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customuser_collectables_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='task_assign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
