# Generated by Django 5.1.6 on 2025-03-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_locations_customuser_collectables_owned'),
        ('home', '0006_customuser_collectables_owned'),
    ]

    operations = [
    ]
