# Generated by Django 5.1.5 on 2025-03-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20250320_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
