# Generated by Django 5.1.6 on 2025-03-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20250321_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
