# Generated by Django 5.1.6 on 2025-03-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customuser_task_assign_date'),
        ('home', '0008_delete_locations'),
    ]

    operations = [
    ]
