# Generated by Django 5.1.3 on 2025-03-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20250322_1330'),
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_riddles',
            field=models.ManyToManyField(blank=True, to='riddles.riddle'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_points',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_points',
            field=models.IntegerField(default=300),
        ),
    ]
