# Generated by Django 5.1.3 on 2025-03-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle_question', models.TextField()),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('week_group', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
            ],
        ),
    ]
